### ISSUE TITLE
Markov decision process aims to maximize long-term cumulative rewards, but there is no relationship between different actions. Is it suitable for reinforcement learning?

### ISSUE THREAD

**Issue by sun9876543** [juanaznarp94/DynamicTPolicy-LoRa#12]
And the observation returned by each episode in the code is the same no matter what action is taken, which feels very strange.Because it seems that reset is called every time the environment is updated, the environment does not change with the change of action.

**Comment by LauraAcostaG** [comment]
Dear @sun9876543, 

many thanks for reaching out. We agree that other methods might be also suitable for solving the transmission parameter selection problem of End devices (ED). As in many related works, we opted to use RL because it focuses on learning the optimal actions of the ED over time under different states,  maximizing the total cumulative reward, in this case, in non-episodic environments.

Regarding the issue about observations staying the same, we did not observe this problem during the evaluation. 

Please, feel free to reach out (lauraacostag4@gmail.com), so that we can further assist you.

Kind regards, 

Laura

**Comment by sun9876543** [comment]
self.state = [CONFIGS[self.i], normalize_value(np.log10(self.ber_th), ber_values),
                      normalize_value(self.snr_measured, snr_values),
                      normalize_value(self.distance_th, distance_values), normalize_value(self.pt, ALLOWED_TPS),
                      self.n / NODES]
      observation = np.array(self.state)   The observed value returned is the random value at the beginning of each training. The logical feeling of the code is to create countless environments and then try it with actions.

**Comment by juanaznarp94** [comment]
Dear @sun9876543 , I am unsure why you think several environments are created. Please, refer to the documentation of Stable Baselines 3 and Farama Gymnasium to know how the training loop works and how it interacts with the custom environment created. We would be glad to organize an online meeting to further discuss your questions and be able to explain how the code works. Please, feel free to send an email to Laura.
